const { check } = require('express-validator')
const { validateResult } = require('../lib/validateResult')

const validateCreate = [
    check('id_user')
        .exists()
        .isString()
        .notEmpty(),
    check('products')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('products_create')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('products_update')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('products_delete')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('category')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('category_create')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('category_update')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('category_delete')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('services')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('services_create')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('services_update')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('services_delete')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('client')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('client_create')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('client_update')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('client_delete')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('supplier')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('supplier_create')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('supplier_update')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('supplier_delete')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('employee')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('employee_create')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('employee_update')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('employee_delete')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('buy')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('buy_return')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('buy_pay')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('sell')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('sell_return')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('sell_pay')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('consult_product')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('consult_invoice')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('consult_movement')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('consult_supplier')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('consult_client')
        .exists()
        .isBoolean()
        .notEmpty(),
    check('setting')
        .exists()
        .isBoolean()
        .notEmpty()
    ,
    (req, res, next) => {
        validateResult(req, res, next)
    }
]

module.exports = { validateCreate }